### ISSUE TITLE
Imports from CritterDB don't work

### ISSUE THREAD

**Issue by bakergo** [HadaIonut/Foundry-Markdown-Importer#12]
It'd be neat if this could import creatures from CritterDB as well. It appears that the biggest blocker is a single space in the markdown in the name field of the creature.

https://critterdb.com:443/#/creature/view/61500b75af3aa903ed207987

Fields which appear to be missing or incorrect:

* The creature isn't imported unless you include a space before the ## and 'Test'.
* Armor Class
* Innate spellcasting spells.

```
> ___
>## Test
>*Gargantuan humanoid, lawful good*
>___
>- **Armor Class** 17 (natural armor)
>- **Hit Points** 56 (16d4 + 16)
>- **Speed** 40 ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|10 (+0)|11 (+0)|12 (+1)|13 (+1)|14 (+2)|15 (+2)|
>___
>- **Saving Throws** Str +3, Dex +3, Con +4, Int +4, Wis +5, Cha +5
>- **Skills** Acrobatics +3
>- **Damage Vulnerabilities** slashing
>- **Damage Resistances** bludgeoning
>- **Damage Immunities** piercing
>- **Condition Immunities** poisoned
>- **Senses** darkvision 120 ft., passive Perception 12
>- **Languages** Common, Dwarvish, Primordial
>- **Challenge** 1/8 (25 XP)
>___
>***Assassinate.*** During its first turn, the test has advantage on attack rolls against any creature that hasn't taken a turn. Any hit the test scores against a surprised creature is a critical hit.
>
>***Innate Spellcasting.*** The test's innate spellcasting ability is Charisma (spell save DC 13, +5 to hit with spell attacks). It can innately cast the following spells, requiring no material components:
>
>At will: *acid splash*
>3/day: *alarm*
>2/day: *animal friendship*
>1/day: *disintegrate*
>
>### Actions
>***Spear.*** *Melee or Ranged Weapon Attack:* +3 to hit, reach 5 ft. or range 20/60 ft., one target. *Hit:* 3 (1d6) piercing damage in melee, or 3 (1d6) piercing damage at range, or 4 (1d8) piercing damage if used with two hands to make a melee attack.
>
>### Reactions
>***Parry.*** The test adds 2 to its AC against one melee attack that would hit it. To do so, the test must see the attacker and be wielding a melee weapon.
>
>
```

**Comment by djohnsonnz** [comment]
Armor class is also an issue with Tetra-cube. The only AC that is correctly calculated is unarmored with dexterity, I assume this is due to how AC is now automated opposed to a static number.

Natural and Flat AC are both set with the flat attribute,
![image](https://user-images.githubusercontent.com/9582890/134904189-53109db2-157c-4d4e-87c0-c764a4507f64.png)

Mage Armor has its own calculation
![image](https://user-images.githubusercontent.com/9582890/134904649-7b9a1e91-5455-49f1-9565-75d53729755a.png)

Equipment is harder and is based compendium item/s (armor, armor+shield and mage armor+shield  also works) it would be nice we could do a compendium lookup on these items similar to spells.

**Comment by bakergo** [comment]
Yeah, I think the compendium lookups for spell-like abilities and AC/armor
may be out of scope for this issue. I'll send a PR for the name thing as it
looks like a pretty simple regex change.

**Comment by HadaIonut** [comment]
Heya, sorry for not commenting on this thread earlier, I was busy with work.

But I really like the idea of supporting CritterDB, and I will start working on it soon. :D

**Comment by HadaIonut** [comment]
I think I have got it working, please have a look at the new update
